FROM getgauge/gocd-node

LABEL MAINTAINER="getgauge"
LABEL VERSION="0.1"
LABEL DESCRIPTION="centos gocd agent with nodejs, git, xvfb"
LABEL REPOSITORY="getgauge/gocd-node-xvfb"

ENV container docker

RUN yum install -y xorg-x11-server-Xvfb
